AWSTemplateFormatVersion: 2010-09-09
Description: >-
  exemplo-cloudformation
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        Stage: !Ref Stage

Resources:
  UserList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AWS::StackName
      Runtime: go1.x
      CodeUri: user/handler/list/
      Handler: main
      Description: Call the AWS Lambda API
      Timeout: 5
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active


Outputs:
  UserListFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt UserList.Arn
  UserListFunctionFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt UserList.Arn